using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using elib_entity;

namespace elib_data.Concrete.EfCore
{
    public static class SeedDatabase
    {
        public static void Seed()
        {
            var context = new LibraryContext();
            if (context.Categories.Count() == 0)
            {
                context.Categories.AddRange(Categories);
            }
            if (context.Books.Count() == 0)
            {
                context.Books.AddRange(Books);
                context.AddRange(BookCategories);
            }
            context.SaveChanges();
        }
        private static Category[] Categories =
        {
            new Category(){name="History",url="history"},
            new Category(){name="Education",url="education"},
            new Category(){name="Child",url="child"},
            new Category(){name="Fantastic",url="fantastic"}
        };
        //kategori idleri elle düzenlemen gerek
        private static Book[] Books ={
            new Book(){bookUrl="https://drive.google.com/file/d/0B7OmNithn8yCcjlJVG9FdDNQOWs/view?resourcekey=0-0usfVsZjukEWshLG9CsuzQ", url="grammer-of-english", name = "Grammer Of English", author = "Geoffrey Leech, Jan Svartvik", description = "The best way of learning English Grammer",imgUrl="https://i.pinimg.com/originals/c6/86/60/c686607678b15026737a2e5302fe428c.jpg"},
            new Book(){bookUrl="https://manybooks.net/book/134558/read#epubcfi(/6/4[item5]!/4/2/1:0)" ,url = "alice-in-wonderland", name = "Alice In Wonderland", author = "J.C. Gorham", description = "The story of a girl named Alice who falls down a rabbit hole into a fantasy world populated by peculiar and anthropomorphic creatures. The tale is filled with allusions to Dodgson's friends.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-14299.jpg?itok=wPpEKSe6"},
            new Book(){bookUrl="https://manybooks.net/book/121056/read#epubcfi(/6/2[coverpage-wrapper]!/4/1:0)" ,url = "gullivers-travels", name = "Gulliver's Travels.", author = "Jonathan Swift", description = "A satire on human nature and a parody of the travellers' tales literary genre, this is widely considered Swift's greatest work as well as one of the indisputable classics of English literature.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-6763.jpg?itok=271pXWiR"},
            new Book(){bookUrl="https://manybooks.net/book/121772/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "peter-pan", name = "Peter Pan", author = "J.M Barrie", description = "A free-spirited and mischievous young boy who can fly and never grows up, Peter Pan spends his never-ending childhood having adventures on the mythical island of Neverland as the leader of the Lost Boys, interacting with fairies, pirates, mermaids, Native Americans, and occasionally ordinary children from the world.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-907.jpg?itok=DsSagxDm"},
            new Book(){bookUrl="https://manybooks.net/book/127836/read#epubcfi(/6/2[item4]!/4/2/1:0)" ,url = "the-time-machine", name = "The Time Machine", author = "H.G Wells", description = "A brilliant fantasy beyond conventional thought....", imgUrl = "https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-7349.jpg?itok=AEnzquEW"},
            new Book(){bookUrl="https://manybooks.net/book/127828/read#epubcfi(/6/2[item3]!/4/2/1:0)" ,url = "invisible-man", name = "The Invisible Man", author = "H.G Wells", description = "The Invisible Man of the title is Griffin, a scientist who theorizes that if a person's refractive index is changed to exactly that of air and his body does not absorb or reflect light, then he will not be visible. He successfully carries out this procedure on himself, but begins to become mentally unstable as a result", imgUrl ="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-7340.jpg?itok=E-rNYNDg"},
            new Book(){bookUrl="https://manybooks.net/book/123098/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "lost-world", name = "The Lost World", author = "Arthur Conan Doyle", description = "Follow Professor Challenger on his expedition to the Tepuyes plateau in South America where prehistoric animals and other extinct creatures still roam -- side by side with prehistoric men and vicious ape-like creatures!",imgUrl= "https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-2294.jpg?itok=YMdLprW-"},
            new Book(){bookUrl=" https://manybooks.net/book/132848/read#epubcfi(/6/2[item4]!/4/2/1:0) " ,url = "pinocchio", name = "Pinocchio", author = "Carlo Collodi", description = " A wooden boy’s adventures.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-12523.jpg?itok=e3xgi2G2"},
            new Book(){bookUrl=" https://manybooks.net/book/125140/read#epubcfi(/6/2[titlepage]!/4/1:0) " ,url = "call-of-the-wild", name = "The Call Of The Wild", author = "Jack London", description = "A domesticated and pampered dog's primordial instincts return when events find him serving as a sled dog in the treacherous, frigid Yukon during the hey-days of the 19th century Gold Rush.", imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-4471.jpg?itok=AnEOGbt5 "},
            new Book(){bookUrl="https://manybooks.net/book/122925/read#epubcfi(/6/2[id00000]!/4/2[id00000]/1:0)" ,url = "robinson-cruse", name = "Robinson Cruse", author = "Daniel Dafoe", description = "Sometimes considered to be the first novel in English, this book is a fictional autobiography of a castaway who spends 28 years on a remote tropical island near Venezuela.",imgUrl=" https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-2118.jpg?itok=5ksVB6SZ"},
            new Book(){bookUrl=" https://manybooks.net/book/123181/read#epubcfi(/6/2[pg-header]!/4/2[the-three-musketeers]/2/2/1:0) " ,url = "three-musketeers", name = "Three Musketeers", author = "Alexandre Dumas", description = " The adventures of a young man named d'Artagnan after he leaves home to become a guard of the musketeers. D'Artagnan is not one of the musketeers of the title; those are his friends Athos, Porthos, and Aramis.",imgUrl=" https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-2382.jpg?itok=bav8KXIW"},
            new Book(){bookUrl=" https://manybooks.net/book/125547/read#epubcfi(/6/2[id00000]!/4/2[id00000]/1:0) " ,url = "anna-karenina", name = "Anna Karenina", author = "Tolstoy", description = " Anna is the jewel of St. Petersburg society until she leaves her husband for the handsome and charming military officer, Count Vronsky. They fall in love, going beyond High Society's acceptance of trivial adulterous dalliances. But when Vronsky's love cools, Anna cannot bring herself to return to the husband she detests.",imgUrl=" https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-6931.jpg?itok=-SyZeD1k"},
            new Book(){bookUrl=" https://manybooks.net/book/121576/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "pride-and-prejudice", name = "Pride And Prejudice", author = "Jane Austen", description = " Austen's finest comedy of manners portrays life in the genteel rural society of the early 1800s, and tells of the initial misunderstandings (and mutual enlightenment) between lively and quick witted Elizabeth Bennet and the haughty Mr. Darcy.",imgUrl=" https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-699.jpg?itok=YMpHxFDI"},
            new Book(){bookUrl="https://manybooks.net/book/123004/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "oliver-twist", name = "Oliver Twist", author = "Charles Dickens", description = " Probably the best-known of all Dickens' works, Oliver Twist was originally published as a serial, and sought to bring the public's attention to various contemporary social evils, including the workhouse, child labour and the recruitment of children as criminals.The novel is full of drama, sarcasm and dark humour even as it reveals the hypocrisies of the time.",imgUrl=" https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-2199.jpg?itok=MMrTGhWz"},
            new Book(){bookUrl="https://manybooks.net/book/136669/read#epubcfi(/6/2[item3]!/4/2/1:0)" ,url = "faust", name = " Faust", author = "Johann Wolfgang von Goethe", description = "The erudite Faust is highly successful yet dissatisfied with his life, which leads him to make a pact with the Devil at a crossroads, exchanging his soul for unlimited knowledge and worldly pleasures. ",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-16494.jpg?itok=Hw0SBRHb"},
            new Book(){bookUrl="https://manybooks.net/book/122453/read#epubcfi(/6/2[id00000]!/4/2[id00000]/1:0)" ,url = "don-quixote", name = "Don Quixote", author = "Miguel de Cervantes", description = " Translated by John Ormsby. One of the earliest novels in a modern European language, one which many people consider the finest book in the Spanish language. ",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-cust-1621.jpg?itok=ch16gxqH"},
            new Book(){bookUrl="https://manybooks.net/book/138013/read#epubcfi(/6/2[item4]!/4/2/1:0)" ,url = "smiles", name = " Smiles", author = "Eliot H. Robinson", description = " Smiles is a girl who has already made many friends and is destined to make many more. Her real name is Rose, but the rough folk of the Cumberlands preferred tehir own way of addressing her, for her smile was so bright and winning that no other name suited her so well.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-17894.jpg?itok=ytpv6MmR"},
            new Book(){bookUrl="https://manybooks.net/book/123813/read#epubcfi(/6/2[item4]!/4/2/1:0)" ,url = "grimms-fairy-tales", name = " Grimms' Fairy Tales", author = "By Jacob Grimm by Wilhelm Grimm", description = " Based on translations of Kinder und Hausmarchen by Edgar Taylor and Marian Edwardes.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-3050.jpg?itok=yZubS0Mt"},
            new Book(){bookUrl="https://manybooks.net/book/122249/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "tarzan-of-the-apes", name = " Tarzan of the Apes", author = "Edgar Rice Burroughs", description = " The novel is the coming-of-age story of John Clayton, born in the western coastal jungles of equatorial Africa to a marooned couple from England, John and Alice Clayton, Lord and Lady Greystoke. Adopted as an infant by the she-ape Kala after his parents are killed by the savage king ape Kerchak, Clayton is renamed Tarzan (''White Skin'' in the ape language) and raised in ignorance of his human heritage.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-1407.jpg?itok=KSUC5y1l"},
            new Book(){bookUrl="https://manybooks.net/book/146002/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "the-treasure-of-atlantis", name = " The Treasure of Atlantis", author = "J. Allan Dunn", description = " In J. Allan Dunn's THE TREASURE OF ATLANTIS, an orchid hunter's discovery is the catalyst that leads an expedition into the interior of South America to the lost remnant of ancient Atlantis. Cut off from the modern world, Atlantis offers swashbuckling intrigue, danger, and action that is eminently suitable for the Time-Lost series. Here is thrilling adventure out of the past in the Edgar Rice Burroughs tradition.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-26212.jpg?itok=ilxMx48d"},
            new Book(){bookUrl="https://manybooks.net/book/147936/read#epubcfi(/6/2[coverpage-wrapper]!/4/1:0)" ,url = "castle-of-terror", name = " Castle of Terror", author = "E. J. Liston", description = " What strange dimension was this where giants, gangsters, Lucretia Borgia, dwarfs and Rip Van Winkle lived at the same time?",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-28206.jpg?itok=ajlDeImO"},
            new Book(){bookUrl="https://manybooks.net/book/135269/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "the-deserted-house", name = " The Deserted House", author = "E. T. A. Hoffmann", description = "Mrs. Warren. Yes yes. Though one can hardly think of any woman unlawfully taking a poor gentleman's trousers",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-auto-15027.jpg?itok=Ny6aYGk1"},
            new Book(){bookUrl="https://manybooks.net/book/147948/read#epubcfi(/6/2[coverpage-wrapper]!/4/1:0)" ,url = "mask-of-death", name = " Mask of Death", author = "Paul Ernst", description = " A weird and uncanny tale about a strange criminal who called himself Doctor Satan, and the terrible doom with which he struck down his enemies.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/migrated-covers/cover-32905.jpg?itok=hIAdaeQ2"},
            new Book(){bookUrl="https://manybooks.net/book/144010/read#epubcfi(/6/2[item4]!/4/2/1:0)" ,url = "the-defenders", name = " The Defenders", author = "Philip K. Dick", description = " No weapon has ever been frightful enough to put a stop to war--perhaps because we never before had any that thought for themselves!",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-orig-24144.jpg?itok=fZKaLwCn"},
            new Book(){bookUrl="https://manybooks.net/book/248256/read#epubcfi(/6/2[Cover]!/4/1:0)" ,url = "love-in-an-undead-age", name = " Love in an Undead Age", author = "A.M. Geever", description = "Mrs. Warren. Yes yes. Though one can hardly think of any woman unlawfully taking a poor gentleman's trousers.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/2021-09/51B2hvqQoIL.jpeg?itok=f2hoi0q-"},
            new Book(){bookUrl="https://manybooks.net/book/249931/read#epubcfi(/6/2[titlepage]!/4/1:0)" ,url = "mostly-dark", name = " Mostly Dark", author = "Miranda Kate", description = " Like the phases of the moon, Mostly Dark waxes and wanes with thirty tales of darkness and light. An intriguing maelstrom of broken minds and broken hearts, from revenge to desire, from new found love to soulmates, herein lies a tale for everyone. Prepare your senses for an emotional and sometimes terrifying ride.",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/2021-12/515GTzpfjJL.jpeg?itok=fYqbH6IX"},
            new Book(){bookUrl="https://manybooks.net/book/248086/read#epubcfi(/6/2[content_0_item_0]!/4/2/2/2/2/1:0)" ,url = "remembrance", name = " Remembrance", author = "T.K. Eldridge", description = " I was three when I watched my mother die.Now I'm back in Muckle Cove digging into her murder.They say coming home is never easy, but what I'm finding goes so much deeper than anyone could have imagined.Ancient magic, modern politics, and my mother's ghost all point to some truth in the past that could change my present forever.If it doesn't kill me first...Grab this first in the five-star series that readers say ...makes you believe in magic!",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/2021-09/Remembrance.jpg?itok=fZc6IKLD"},
            new Book(){bookUrl="https://manybooks.net/book/151137/read#epubcfi(/6/2[item4]!/4/2/1:0)" ,url = "pirates", name = "Pirates ", author = "Colin Campbell Clements", description = "",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/old-covers/cover-auto-31518.jpg?itok=lnZOAKcs"},
            new Book(){bookUrl="https://manybooks.net/book/211331/read#epubcfi(/6/2[coverpage-wrapper]!/4/1:0)" ,url = "socrates", name = " Socrates", author = "Antonio Labriola", description = "Life of Socrates",imgUrl="https://manybooks.net/sites/default/files/styles/220x330sc/public/migrated-covers/cover-59064.jpg?itok=h1wja86c"}
        };
        //Every book should be added to "all categories" to display every book in every category


        private static BookCategory[] BookCategories ={
            new BookCategory(){Book = Books[0], category = Categories[0]},
            new BookCategory(){Book = Books[0], category = Categories[1]},
            new BookCategory(){Book = Books[1], category = Categories[1]},
            new BookCategory(){Book = Books[2], category = Categories[0]},
            new BookCategory(){Book = Books[2], category = Categories[2]},


        };
    }
}